// generated by `make` -- boot ROM blob offsets + sizes (do not edit)
#define FUBOOT_OPENSBI_OFF  0x10000UL
#define FUBOOT_OPENSBI_SIZE 275728UL
#define FUBOOT_UBOOT_OFF    0x60000UL
#define FUBOOT_UBOOT_SIZE   512437UL
#define FUBOOT_DTB_OFF      0xF0000UL
#define FUBOOT_DTB_SIZE     2811UL
