//	vcu118_ddr_top.v
//	=== VCU118 board top with DDR4 (MIG) main memory.  [board-gated scaffolding]
//
//	Same SoC as vcu118_top.v, but main memory is the DDR4 SODIMM reached via the
//	Xilinx DDR4 (MIG) IP instead of on-chip BRAM. Structure:
//
//	    karu64 (imem+dmem) -> karu_ddr_xbar -> [64-bit AXI4 @ 75/100 MHz]
//	        -> axi_clock_converter_0 -> [64-bit AXI4 @ MIG ui_clk]
//	        -> host/CPU mux -> axi_dwidth_converter_0 (64 -> 512)
//	        -> ddr4_0 c0_ddr4_s_axi (512)
//	    jtag_axi_0 -> karu_jtag_axi64_loader -> host/CPU mux
//	    CLINT/PLIC/NS16550 stay on-chip inside karu_ddr_xbar.
//
//	Clocking/reset: the core runs at MIG ui_clk / KARU_DDR_CPU_DIV. Board-preset
//	DDR4-2400 uses a 300 MHz ui_clk (default /3 = 100 MHz, /4 = 75 MHz).
//	KARU_DDR4_CUSTOM_2133 is only for the experimental custom 2133 MT/s MIG
//	generated by flow/fpga/mig_vcu118.tcl; default builds leave it undefined and use
//	the board preset. The experimental MIG's resolved ui_clk is 266.5 MHz. Reset
//	is held until DDR4 calibration completes (c0_init_calib_complete) and the MIG
//	UI reset deasserts, then the CPU boots automatically from the on-chip fu-boot
//	ROM at RESET_PC=0x0000_1000, which loads/inflates payloads into DDR and jumps
//	to 0x8000_0000. (The legacy DDR4-debug scaffolding -- VIO probe_out0[0] CPU
//	hold + the jtag_axi_0 load-then-release host loader -- is now compiled out by
//	default and only returns under `KARU_DDR_HOST_DBG`.)
//
//	*** NOT yet hardware-validated (no VCU118 attached). ***  The ddr4_0 and
//	axi_dwidth_converter_0 instances are black boxes until generated
//	(`make mig-vcu118`); reconcile their port names/widths with the generated
//	ddr4_0.veo / converter .veo before synthesis. The DDR4 PHY pins below are
//	the standard MIG c0_ddr4_* bus; the MIG generates their pin XDC.

`include "config.vh"
`include "karu_axi_defs.vh"

`ifndef SIM_TB
//	NOTE: the LiteEth MAC/register path is wired into the DDR SoC for hardware
//	timing probes. The external VCU118 SGMII/DP83867 PHY front-end is still a
//	separate board-link step; this top currently exposes no Ethernet pins.
module vcu118_ddr_top (
	//	DDR4 system reference clock (250 MHz, DIFF_SSTL12, pins E12/D12)
	input  wire			c0_sys_clk_p,
	input  wire			c0_sys_clk_n,
	//	DDR4 SODIMM PHY (MIG-owned pins; constrained by the generated IP XDC)
	output wire [16:0]	c0_ddr4_adr,
	output wire [1:0]	c0_ddr4_ba,
	output wire [0:0]	c0_ddr4_bg,
	output wire			c0_ddr4_act_n,
	output wire [0:0]	c0_ddr4_cke,
	output wire [0:0]	c0_ddr4_odt,
	output wire [0:0]	c0_ddr4_cs_n,
	output wire [0:0]	c0_ddr4_ck_t,
	output wire [0:0]	c0_ddr4_ck_c,
	output wire			c0_ddr4_reset_n,
	inout  wire [7:0]	c0_ddr4_dm_dbi_n,
	inout  wire [63:0]	c0_ddr4_dq,
	inout  wire [7:0]	c0_ddr4_dqs_t,
	inout  wire [7:0]	c0_ddr4_dqs_c,
	//	console + control
	output wire			usb_uart_txd_o,
	input  wire			usb_uart_rxd_i,
	output wire			usb_uart_rts_o,
	input  wire			usb_uart_cts_i,
	input  wire			btn_rst_i,
	input  wire	[4:0]	btn_i,
	output wire [7:0]	led_o
`ifdef KARU_ETH_PHY
	//	DP83867 MDIO management front-end (SelectIO/LVCMOS18 pins in
	//	flow/fpga/eth/dp83867_mdio_pins.xdc).
	,output wire		eth_mdc,
	 inout  wire		eth_mdio,
	 output wire		eth_phy_reset_n
`endif
`ifdef KARU_ETH_SGMII
	//	SGMII to the DP83867 over SelectIO/LVDS (pins in flow/fpga/eth/sgmii_pins.xdc): the
	//	625 MHz LVDS ref clock + the serial TX/RX LVDS pairs. KARU_ETH_SGMII requires
	//	KARU_ETH_PHY (enforced in flow/fpga/xcvu9p-ddr-synth.tcl + the make target).
	,input  wire		eth_sgmii_clk_p,
	 input  wire		eth_sgmii_clk_n,
	 output wire		eth_sgmii_txp,
	 output wire		eth_sgmii_txn,
	 input  wire		eth_sgmii_rxp,
	 input  wire		eth_sgmii_rxn
`endif
);
	//	===== MIG clock / reset / calibration =====
`ifndef KARU_DDR_CPU_DIV
`define KARU_DDR_CPU_DIV 3
`endif
	localparam integer CPU_CLK_DIV = `KARU_DDR_CPU_DIV;
`ifdef KARU_DDR4_CUSTOM_2133
	localparam [31:0] MIG_UI_CLK_HZ = 32'd266500000;
`else
	localparam [31:0] MIG_UI_CLK_HZ = 32'd300000000;
`endif
	localparam [31:0] CPU_CLK_HZ = MIG_UI_CLK_HZ / CPU_CLK_DIV;
	localparam integer UART_BITCLKS = CPU_CLK_HZ / 115200;
											// NB: the FPGA console is wired to the CP2105
											// Standard (SCI) port (/dev/ttyUSB1), max 921600
											// baud -- the old 2 Mbaud (BITCLKS=50) was
											// unreadable. Keep <= 921600.
	localparam integer CLINT_TICK_DIV = CPU_CLK_HZ / 1000000;	// 1 MHz mtime tick
	wire _unused_params = &{CPU_CLK_HZ[0], 1'b0};

	wire		ui_clk;					//	MIG user clock
	wire		ui_clk_sync_rst;		//	MIG user reset (active high, sync to ui_clk)
	wire		init_calib_complete;	//	high once DDR4 is trained
	wire		c0_ddr4_aresetn;		//	AXI reset (active low) into MIG/converter

	wire		sys_rst = btn_rst_i ^ btn_i[4];	//	async board reset request
`ifdef KARU_DDR_HOST_DBG
	wire [1:0]	host_ctl;
	wire		host_cpu_hold = host_ctl[0];		//	VIO default=1: hold CPU for JTAG-AXI DRAM load
	wire		host_cpu_reset = host_ctl[1];	//	manual reset pulse/level
`else
	//	DDR4-debug hold + JTAG-AXI host loader removed: the CPU comes out of reset
	//	automatically once MIG calibration completes and owns the DRAM AXI directly.
	//	(const-0 so core_arst / use_host_axi / led_o below resolve unchanged.)
	wire		host_cpu_hold = 1'b0;
	wire		host_cpu_reset = 1'b0;
`endif
	wire		trap;

	//	Core reset: held while MIG resets or DDR4 is not yet calibrated, then a
	//	short conditioned release. CPU clock is ui_clk / CPU_CLK_DIV.
	wire		cpu_clk;
	BUFGCE_DIV #(
		.BUFGCE_DIVIDE	(CPU_CLK_DIV)
	) u_cpu_clk_div (
		.I	(ui_clk),
		.CE	(1'b1),
		.CLR(1'b0),
		.O	(cpu_clk)
	);
	wire		core_arst = ui_clk_sync_rst | ~init_calib_complete | sys_rst |
							host_cpu_hold | host_cpu_reset;
	wire		ui_axi_arst = ui_clk_sync_rst | ~init_calib_complete | sys_rst;
	wire		clk = cpu_clk;
	wire		rst;
	reset_ctrl #(.POR_CYCLES(64)) u_rst (
		.clk(clk), .arst_in(core_arst), .rst_out(rst)
	);
	wire		ui_axi_rst;
	reset_ctrl #(.POR_CYCLES(64)) u_ui_axi_rst (
		.clk(ui_clk), .arst_in(ui_axi_arst), .rst_out(ui_axi_rst)
	);
	assign c0_ddr4_aresetn = ~ui_axi_rst;

`ifdef KARU_DDR_HOST_DBG
	(* ASYNC_REG = "TRUE" *) reg [1:0] rst_ui_sync = 2'b11;
	(* ASYNC_REG = "TRUE" *) reg [1:0] trap_ui_sync = 2'b00;
	always @(posedge ui_clk) begin
		rst_ui_sync <= {rst_ui_sync[0], rst};
		trap_ui_sync <= {trap_ui_sync[0], trap};
	end
`endif

	//	===== Eth SGMII datapath nets (xbar MAC GMII <-> board-top PCS/PMA) + status =====
	wire [15:0]	eth_status_ui;		//	PCS status_vector synced to ui_clk -> VIO probe_in1
`ifdef KARU_ETH_SGMII
	wire [7:0]	eth_gmii_txd;		//	MAC -> PCS
	wire		eth_gmii_tx_en, eth_gmii_tx_er;
	wire [7:0]	eth_gmii_rxd;		//	PCS -> MAC
	wire		eth_gmii_rx_dv, eth_gmii_rx_er;
	wire		eth_clk125;			//	PCS clk125_out -> MAC GMII clock
	wire [15:0]	eth_pcs_status;		//	PCS status_vector_0 (link/speed/AN)
	(* ASYNC_REG = "TRUE" *) reg [15:0] eth_st_s0 = 16'b0, eth_st_s1 = 16'b0;
	always @(posedge ui_clk) begin
		eth_st_s0 <= eth_pcs_status;
		eth_st_s1 <= eth_st_s0;
	end
	assign eth_status_ui = eth_st_s1;
`else
	assign eth_status_ui = 16'b0;
`endif

`ifdef KARU_DDR_HOST_DBG
	vio_0 u_host_ctl (
		.clk(ui_clk),
		.probe_in0({trap_ui_sync[1], init_calib_complete, ui_clk_sync_rst,
					ui_axi_rst, rst_ui_sync[1], host_cpu_reset,
					host_cpu_hold, 1'b0}),
		.probe_in1(eth_status_ui),
		.probe_out0(host_ctl)
	);
`endif

	//	===== SoC: karu64 + xbar (DRAM AXI4 master exposed) =====
	wire		uart_txd, uart_rxd, uart_rts;
	assign		uart_rxd = usb_uart_rxd_i;
	assign		usb_uart_txd_o = uart_txd;
	assign		usb_uart_rts_o = ~uart_rts;

	//	imem/dmem (core <-> xbar)
	wire [`AXI_ID_W-1:0]	imem_arid;   wire [`AXI_ADDR_W-1:0] imem_araddr;
	wire [`AXI_LEN_W-1:0]	imem_arlen;  wire [`AXI_SIZE_W-1:0] imem_arsize;
	wire [`AXI_BURST_W-1:0]	imem_arburst; wire [`AXI_PROT_W-1:0] imem_arprot;
	wire					imem_arvalid, imem_arready;
	wire [`AXI_ID_W-1:0]	imem_rid;    wire [`AXI_DATA_W-1:0] imem_rdata;
	wire [`AXI_RESP_W-1:0]	imem_rresp;  wire imem_rlast, imem_rvalid, imem_rready;
	wire [`AXI_ID_W-1:0]	dmem_arid;   wire [`AXI_ADDR_W-1:0] dmem_araddr;
	wire [`AXI_LEN_W-1:0]	dmem_arlen;  wire [`AXI_SIZE_W-1:0] dmem_arsize;
	wire [`AXI_BURST_W-1:0]	dmem_arburst; wire [`AXI_PROT_W-1:0] dmem_arprot;
	wire					dmem_arvalid, dmem_arready;
	wire [`AXI_ID_W-1:0]	dmem_rid;    wire [`AXI_DATA_W-1:0] dmem_rdata;
	wire [`AXI_RESP_W-1:0]	dmem_rresp;  wire dmem_rlast, dmem_rvalid, dmem_rready;
	wire [`AXI_ID_W-1:0]	dmem_awid;   wire [`AXI_ADDR_W-1:0] dmem_awaddr;
	wire [`AXI_LEN_W-1:0]	dmem_awlen;  wire [`AXI_SIZE_W-1:0] dmem_awsize;
	wire [`AXI_BURST_W-1:0]	dmem_awburst; wire [`AXI_PROT_W-1:0] dmem_awprot;
	wire					dmem_awvalid, dmem_awready;
	wire [`AXI_DATA_W-1:0]	dmem_wdata;  wire [`AXI_STRB_W-1:0] dmem_wstrb;
	wire					dmem_wlast, dmem_wvalid, dmem_wready;
	wire [`AXI_ID_W-1:0]	dmem_bid;    wire [`AXI_RESP_W-1:0] dmem_bresp;
	wire					dmem_bvalid, dmem_bready;

	//	xbar DRAM master (64-bit, CPU clock) -> clock converter
	wire [`AXI_ID_W-1:0]	x_arid;   wire [`AXI_ADDR_W-1:0] x_araddr;
	wire [`AXI_LEN_W-1:0]	x_arlen;  wire [`AXI_SIZE_W-1:0] x_arsize;
	wire [`AXI_BURST_W-1:0]	x_arburst; wire x_arvalid, x_arready;
	wire [`AXI_ID_W-1:0]	x_rid;    wire [`AXI_DATA_W-1:0] x_rdata;
	wire [`AXI_RESP_W-1:0]	x_rresp;  wire x_rlast, x_rvalid, x_rready;
	wire [`AXI_ID_W-1:0]	x_awid;   wire [`AXI_ADDR_W-1:0] x_awaddr;
	wire [`AXI_LEN_W-1:0]	x_awlen;  wire [`AXI_SIZE_W-1:0] x_awsize;
	wire [`AXI_BURST_W-1:0]	x_awburst; wire x_awvalid, x_awready;
	wire [`AXI_DATA_W-1:0]	x_wdata;  wire [`AXI_STRB_W-1:0] x_wstrb;
	wire					x_wlast, x_wvalid, x_wready;
	wire [`AXI_ID_W-1:0]	x_bid;    wire [`AXI_RESP_W-1:0] x_bresp;
	wire					x_bvalid, x_bready;

	//	clock converter master (64-bit, MIG ui_clk) -> data-width converter
	wire [`AXI_ID_W-1:0]	c_arid;   wire [30:0] c_araddr;
	wire [`AXI_LEN_W-1:0]	c_arlen;  wire [2:0] c_arsize;
	wire [1:0]				c_arburst; wire [0:0] c_arlock;
	wire [3:0]				c_arcache; wire [2:0] c_arprot;
	wire [3:0]				c_arregion, c_arqos;
	wire					c_arvalid, c_arready;
	wire [`AXI_ID_W-1:0]	c_rid;    wire [63:0] c_rdata;
	wire [1:0]				c_rresp;  wire c_rlast, c_rvalid, c_rready;
	wire [`AXI_ID_W-1:0]	c_awid;   wire [30:0] c_awaddr;
	wire [`AXI_LEN_W-1:0]	c_awlen;  wire [2:0] c_awsize;
	wire [1:0]				c_awburst; wire [0:0] c_awlock;
	wire [3:0]				c_awcache; wire [2:0] c_awprot;
	wire [3:0]				c_awregion, c_awqos;
	wire					c_awvalid, c_awready;
	wire [63:0]				c_wdata;  wire [7:0] c_wstrb;
	wire					c_wlast, c_wvalid, c_wready;
	wire [`AXI_ID_W-1:0]	c_bid;    wire [1:0] c_bresp;
	wire					c_bvalid, c_bready;

`ifdef KARU_DDR_HOST_DBG
	//	JTAG AXI master (32-bit, MIG ui_clk) -> loader adapter
	wire [0:0]				j_awid;   wire [31:0] j_awaddr;
	wire [7:0]				j_awlen;  wire [2:0] j_awsize; wire [1:0] j_awburst;
	wire					j_awlock; wire [3:0] j_awcache; wire [2:0] j_awprot;
	wire [3:0]				j_awqos;  wire j_awvalid, j_awready;
	wire [31:0]				j_wdata;  wire [3:0] j_wstrb;
	wire					j_wlast, j_wvalid, j_wready;
	wire [0:0]				j_bid;    wire [1:0] j_bresp;
	wire					j_bvalid, j_bready;
	wire [0:0]				j_arid;   wire [31:0] j_araddr;
	wire [7:0]				j_arlen;  wire [2:0] j_arsize; wire [1:0] j_arburst;
	wire					j_arlock; wire [3:0] j_arcache; wire [2:0] j_arprot;
	wire [3:0]				j_arqos;  wire j_arvalid, j_arready;
	wire [0:0]				j_rid;    wire [31:0] j_rdata;
	wire [1:0]				j_rresp;  wire j_rlast, j_rvalid, j_rready;

	//	Host-loader 64-bit AXI (MIG ui_clk) -> host/CPU mux
	wire [`AXI_ID_W-1:0]	h_arid;   wire [30:0] h_araddr;
	wire [`AXI_LEN_W-1:0]	h_arlen;  wire [2:0] h_arsize;
	wire [1:0]				h_arburst; wire h_arlock;
	wire [3:0]				h_arcache; wire [2:0] h_arprot;
	wire [3:0]				h_arregion, h_arqos;
	wire					h_arvalid, h_arready;
	wire [`AXI_ID_W-1:0]	h_rid;    wire [63:0] h_rdata;
	wire [1:0]				h_rresp;  wire h_rlast, h_rvalid, h_rready;
	wire [`AXI_ID_W-1:0]	h_awid;   wire [30:0] h_awaddr;
	wire [`AXI_LEN_W-1:0]	h_awlen;  wire [2:0] h_awsize;
	wire [1:0]				h_awburst; wire h_awlock;
	wire [3:0]				h_awcache; wire [2:0] h_awprot;
	wire [3:0]				h_awregion, h_awqos;
	wire					h_awvalid, h_awready;
	wire [63:0]				h_wdata;  wire [7:0] h_wstrb;
	wire					h_wlast, h_wvalid, h_wready;
	wire [`AXI_ID_W-1:0]	h_bid;    wire [1:0] h_bresp;
	wire					h_bvalid, h_bready;

	//	Host side selected only while the CPU is held (load-then-release flow).
	wire					use_host_axi = host_cpu_hold;
`endif
	wire [`AXI_ID_W-1:0]	s_arid;   wire [30:0] s_araddr;
	wire [`AXI_LEN_W-1:0]	s_arlen;  wire [2:0] s_arsize;
	wire [1:0]				s_arburst; wire s_arlock;
	wire [3:0]				s_arcache; wire [2:0] s_arprot;
	wire [3:0]				s_arregion, s_arqos;
	wire					s_arvalid, s_arready;
	wire [`AXI_ID_W-1:0]	s_rid;    wire [63:0] s_rdata;
	wire [1:0]				s_rresp;  wire s_rlast, s_rvalid, s_rready;
	wire [`AXI_ID_W-1:0]	s_awid;   wire [30:0] s_awaddr;
	wire [`AXI_LEN_W-1:0]	s_awlen;  wire [2:0] s_awsize;
	wire [1:0]				s_awburst; wire s_awlock;
	wire [3:0]				s_awcache; wire [2:0] s_awprot;
	wire [3:0]				s_awregion, s_awqos;
	wire					s_awvalid, s_awready;
	wire [63:0]				s_wdata;  wire [7:0] s_wstrb;
	wire					s_wlast, s_wvalid, s_wready;
	wire [`AXI_ID_W-1:0]	s_bid;    wire [1:0] s_bresp;
	wire					s_bvalid, s_bready;

	wire		irq_timer, irq_ext_m, irq_ext_s;
	wire [63:0]	clint_mtime;		//	CLINT mtime -> CSR rdtime (shared timer domain)

	karu64 #(.RESET_PC(32'h0000_1000), .EXT_TIME(1)) cpu (
		.clk(clk), .rst(rst), .trap(trap),
		.irq(irq_timer), .irq_external_m(irq_ext_m), .irq_external_s(irq_ext_s),
		.time_in(clint_mtime),
		.hpm_events(32'b0),
		.cache_flush_req(), .cache_flush_invalidate(), .cache_flush_done(1'b1),
		.uncache_page(32'h1000_0000),
		.imem_arid(imem_arid), .imem_araddr(imem_araddr), .imem_arlen(imem_arlen),
		.imem_arsize(imem_arsize), .imem_arburst(imem_arburst), .imem_arprot(imem_arprot),
		.imem_arvalid(imem_arvalid), .imem_arready(imem_arready),
		.imem_rid(imem_rid), .imem_rdata(imem_rdata), .imem_rresp(imem_rresp),
		.imem_rlast(imem_rlast), .imem_rvalid(imem_rvalid), .imem_rready(imem_rready),
		.dmem_arid(dmem_arid), .dmem_araddr(dmem_araddr), .dmem_arlen(dmem_arlen),
		.dmem_arsize(dmem_arsize), .dmem_arburst(dmem_arburst), .dmem_arprot(dmem_arprot),
		.dmem_arvalid(dmem_arvalid), .dmem_arready(dmem_arready),
		.dmem_rid(dmem_rid), .dmem_rdata(dmem_rdata), .dmem_rresp(dmem_rresp),
		.dmem_rlast(dmem_rlast), .dmem_rvalid(dmem_rvalid), .dmem_rready(dmem_rready),
		.dmem_awid(dmem_awid), .dmem_awaddr(dmem_awaddr), .dmem_awlen(dmem_awlen),
		.dmem_awsize(dmem_awsize), .dmem_awburst(dmem_awburst), .dmem_awprot(dmem_awprot),
		.dmem_awvalid(dmem_awvalid), .dmem_awready(dmem_awready),
		.dmem_wdata(dmem_wdata), .dmem_wstrb(dmem_wstrb), .dmem_wlast(dmem_wlast),
		.dmem_wvalid(dmem_wvalid), .dmem_wready(dmem_wready),
		.dmem_bid(dmem_bid), .dmem_bresp(dmem_bresp),
		.dmem_bvalid(dmem_bvalid), .dmem_bready(dmem_bready)
	);

	karu_ddr_xbar #(
		.BITCLKS(UART_BITCLKS),
		.TICK_DIV(CLINT_TICK_DIV),
		.ROM_HEX("vcu118_fuboot.hex")
	) xbar (
		.clk(clk), .rst(rst),
		.imem_arid(imem_arid), .imem_araddr(imem_araddr), .imem_arlen(imem_arlen),
		.imem_arsize(imem_arsize), .imem_arburst(imem_arburst), .imem_arprot(imem_arprot),
		.imem_arvalid(imem_arvalid), .imem_arready(imem_arready),
		.imem_rid(imem_rid), .imem_rdata(imem_rdata), .imem_rresp(imem_rresp),
		.imem_rlast(imem_rlast), .imem_rvalid(imem_rvalid), .imem_rready(imem_rready),
		.dmem_arid(dmem_arid), .dmem_araddr(dmem_araddr), .dmem_arlen(dmem_arlen),
		.dmem_arsize(dmem_arsize), .dmem_arburst(dmem_arburst), .dmem_arprot(dmem_arprot),
		.dmem_arvalid(dmem_arvalid), .dmem_arready(dmem_arready),
		.dmem_rid(dmem_rid), .dmem_rdata(dmem_rdata), .dmem_rresp(dmem_rresp),
		.dmem_rlast(dmem_rlast), .dmem_rvalid(dmem_rvalid), .dmem_rready(dmem_rready),
		.dmem_awid(dmem_awid), .dmem_awaddr(dmem_awaddr), .dmem_awlen(dmem_awlen),
		.dmem_awsize(dmem_awsize), .dmem_awburst(dmem_awburst), .dmem_awprot(dmem_awprot),
		.dmem_awvalid(dmem_awvalid), .dmem_awready(dmem_awready),
		.dmem_wdata(dmem_wdata), .dmem_wstrb(dmem_wstrb), .dmem_wlast(dmem_wlast),
		.dmem_wvalid(dmem_wvalid), .dmem_wready(dmem_wready),
		.dmem_bid(dmem_bid), .dmem_bresp(dmem_bresp),
		.dmem_bvalid(dmem_bvalid), .dmem_bready(dmem_bready),
		.m_arid(x_arid), .m_araddr(x_araddr), .m_arlen(x_arlen),
		.m_arsize(x_arsize), .m_arburst(x_arburst),
		.m_arvalid(x_arvalid), .m_arready(x_arready),
		.m_rid(x_rid), .m_rdata(x_rdata), .m_rresp(x_rresp),
		.m_rlast(x_rlast), .m_rvalid(x_rvalid), .m_rready(x_rready),
		.m_awid(x_awid), .m_awaddr(x_awaddr), .m_awlen(x_awlen),
		.m_awsize(x_awsize), .m_awburst(x_awburst),
		.m_awvalid(x_awvalid), .m_awready(x_awready),
		.m_wdata(x_wdata), .m_wstrb(x_wstrb), .m_wlast(x_wlast),
		.m_wvalid(x_wvalid), .m_wready(x_wready),
		.m_bid(x_bid), .m_bresp(x_bresp), .m_bvalid(x_bvalid), .m_bready(x_bready),
		.uart_txd(uart_txd), .uart_rxd(uart_rxd),
		.uart_rts(uart_rts), .uart_cts(~usb_uart_cts_i),
		.irq_timer(irq_timer), .irq_ext_m(irq_ext_m), .irq_ext_s(irq_ext_s),
		.clint_mtime(clint_mtime)
`ifdef KARU_ETH_SGMII
		,.eth_clk125(eth_clk125),
		.gmii_tx_data(eth_gmii_txd), .gmii_tx_en(eth_gmii_tx_en), .gmii_tx_er(eth_gmii_tx_er),
		.gmii_rx_data(eth_gmii_rxd), .gmii_rx_dv(eth_gmii_rx_dv), .gmii_rx_er(eth_gmii_rx_er)
`endif
	);

	//	===== CPU-clock -> MIG-ui-clock AXI4 clock converter =====
	axi_clock_converter_0 u_cdc (
		.s_axi_aclk(clk), .s_axi_aresetn(~rst),
		.s_axi_awid(x_awid), .s_axi_awaddr(x_awaddr[30:0]), .s_axi_awlen(x_awlen),
		.s_axi_awsize(x_awsize), .s_axi_awburst(x_awburst), .s_axi_awlock(1'b0),
		.s_axi_awcache(4'b0011), .s_axi_awprot(3'b000),
		.s_axi_awregion(4'b0000), .s_axi_awqos(4'b0000),
		.s_axi_awvalid(x_awvalid), .s_axi_awready(x_awready),
		.s_axi_wdata(x_wdata), .s_axi_wstrb(x_wstrb), .s_axi_wlast(x_wlast),
		.s_axi_wvalid(x_wvalid), .s_axi_wready(x_wready),
		.s_axi_bid(x_bid), .s_axi_bresp(x_bresp), .s_axi_bvalid(x_bvalid), .s_axi_bready(x_bready),
		.s_axi_arid(x_arid), .s_axi_araddr(x_araddr[30:0]), .s_axi_arlen(x_arlen),
		.s_axi_arsize(x_arsize), .s_axi_arburst(x_arburst), .s_axi_arlock(1'b0),
		.s_axi_arcache(4'b0011), .s_axi_arprot(3'b000),
		.s_axi_arregion(4'b0000), .s_axi_arqos(4'b0000),
		.s_axi_arvalid(x_arvalid), .s_axi_arready(x_arready),
		.s_axi_rid(x_rid), .s_axi_rdata(x_rdata), .s_axi_rresp(x_rresp),
		.s_axi_rlast(x_rlast), .s_axi_rvalid(x_rvalid), .s_axi_rready(x_rready),
		.m_axi_aclk(ui_clk), .m_axi_aresetn(c0_ddr4_aresetn),
		.m_axi_awid(c_awid), .m_axi_awaddr(c_awaddr), .m_axi_awlen(c_awlen),
		.m_axi_awsize(c_awsize), .m_axi_awburst(c_awburst), .m_axi_awlock(c_awlock),
		.m_axi_awcache(c_awcache), .m_axi_awprot(c_awprot),
		.m_axi_awregion(c_awregion), .m_axi_awqos(c_awqos),
		.m_axi_awvalid(c_awvalid), .m_axi_awready(c_awready),
		.m_axi_wdata(c_wdata), .m_axi_wstrb(c_wstrb), .m_axi_wlast(c_wlast),
		.m_axi_wvalid(c_wvalid), .m_axi_wready(c_wready),
		.m_axi_bid(c_bid), .m_axi_bresp(c_bresp), .m_axi_bvalid(c_bvalid), .m_axi_bready(c_bready),
		.m_axi_arid(c_arid), .m_axi_araddr(c_araddr), .m_axi_arlen(c_arlen),
		.m_axi_arsize(c_arsize), .m_axi_arburst(c_arburst), .m_axi_arlock(c_arlock),
		.m_axi_arcache(c_arcache), .m_axi_arprot(c_arprot),
		.m_axi_arregion(c_arregion), .m_axi_arqos(c_arqos),
		.m_axi_arvalid(c_arvalid), .m_axi_arready(c_arready),
		.m_axi_rid(c_rid), .m_axi_rdata(c_rdata), .m_axi_rresp(c_rresp),
		.m_axi_rlast(c_rlast), .m_axi_rvalid(c_rvalid), .m_axi_rready(c_rready)
	);

`ifdef KARU_DDR_HOST_DBG
	//	===== JTAG-to-AXI host loader (active while host_cpu_hold=1) =====
	jtag_axi_0 u_jtag_axi (
		.aclk(ui_clk), .aresetn(c0_ddr4_aresetn),
		.m_axi_awid(j_awid), .m_axi_awaddr(j_awaddr), .m_axi_awlen(j_awlen),
		.m_axi_awsize(j_awsize), .m_axi_awburst(j_awburst), .m_axi_awlock(j_awlock),
		.m_axi_awcache(j_awcache), .m_axi_awprot(j_awprot), .m_axi_awqos(j_awqos),
		.m_axi_awvalid(j_awvalid), .m_axi_awready(j_awready),
		.m_axi_wdata(j_wdata), .m_axi_wstrb(j_wstrb), .m_axi_wlast(j_wlast),
		.m_axi_wvalid(j_wvalid), .m_axi_wready(j_wready),
		.m_axi_bid(j_bid), .m_axi_bresp(j_bresp), .m_axi_bvalid(j_bvalid),
		.m_axi_bready(j_bready),
		.m_axi_arid(j_arid), .m_axi_araddr(j_araddr), .m_axi_arlen(j_arlen),
		.m_axi_arsize(j_arsize), .m_axi_arburst(j_arburst), .m_axi_arlock(j_arlock),
		.m_axi_arcache(j_arcache), .m_axi_arprot(j_arprot), .m_axi_arqos(j_arqos),
		.m_axi_arvalid(j_arvalid), .m_axi_arready(j_arready),
		.m_axi_rid(j_rid), .m_axi_rdata(j_rdata), .m_axi_rresp(j_rresp),
		.m_axi_rlast(j_rlast), .m_axi_rvalid(j_rvalid), .m_axi_rready(j_rready)
	);

	karu_jtag_axi64_loader u_jtag_loader (
		.clk(ui_clk), .rst(ui_axi_rst | ~host_cpu_hold),
		.s_awid(j_awid), .s_awaddr(j_awaddr), .s_awlen(j_awlen),
		.s_awsize(j_awsize), .s_awburst(j_awburst),
		.s_awvalid(j_awvalid), .s_awready(j_awready),
		.s_wdata(j_wdata), .s_wstrb(j_wstrb), .s_wlast(j_wlast),
		.s_wvalid(j_wvalid), .s_wready(j_wready),
		.s_bid(j_bid), .s_bresp(j_bresp), .s_bvalid(j_bvalid),
		.s_bready(j_bready),
		.s_arid(j_arid), .s_araddr(j_araddr), .s_arlen(j_arlen),
		.s_arsize(j_arsize), .s_arburst(j_arburst),
		.s_arvalid(j_arvalid), .s_arready(j_arready),
		.s_rid(j_rid), .s_rdata(j_rdata), .s_rresp(j_rresp),
		.s_rlast(j_rlast), .s_rvalid(j_rvalid), .s_rready(j_rready),
		.m_awid(h_awid), .m_awaddr(h_awaddr), .m_awlen(h_awlen),
		.m_awsize(h_awsize), .m_awburst(h_awburst), .m_awlock(h_awlock),
		.m_awcache(h_awcache), .m_awprot(h_awprot), .m_awregion(h_awregion),
		.m_awqos(h_awqos), .m_awvalid(h_awvalid), .m_awready(h_awready),
		.m_wdata(h_wdata), .m_wstrb(h_wstrb), .m_wlast(h_wlast),
		.m_wvalid(h_wvalid), .m_wready(h_wready),
		.m_bid(h_bid), .m_bresp(h_bresp), .m_bvalid(h_bvalid),
		.m_bready(h_bready),
		.m_arid(h_arid), .m_araddr(h_araddr), .m_arlen(h_arlen),
		.m_arsize(h_arsize), .m_arburst(h_arburst), .m_arlock(h_arlock),
		.m_arcache(h_arcache), .m_arprot(h_arprot), .m_arregion(h_arregion),
		.m_arqos(h_arqos), .m_arvalid(h_arvalid), .m_arready(h_arready),
		.m_rid(h_rid), .m_rdata(h_rdata), .m_rresp(h_rresp),
		.m_rlast(h_rlast), .m_rvalid(h_rvalid), .m_rready(h_rready)
	);

	assign s_awid = use_host_axi ? h_awid : c_awid;
	assign s_awaddr = use_host_axi ? h_awaddr : c_awaddr;
	assign s_awlen = use_host_axi ? h_awlen : c_awlen;
	assign s_awsize = use_host_axi ? h_awsize : c_awsize;
	assign s_awburst = use_host_axi ? h_awburst : c_awburst;
	assign s_awlock = use_host_axi ? h_awlock : c_awlock;
	assign s_awcache = use_host_axi ? h_awcache : c_awcache;
	assign s_awprot = use_host_axi ? h_awprot : c_awprot;
	assign s_awregion = use_host_axi ? h_awregion : c_awregion;
	assign s_awqos = use_host_axi ? h_awqos : c_awqos;
	assign s_awvalid = use_host_axi ? h_awvalid : c_awvalid;
	assign h_awready = use_host_axi ? s_awready : 1'b0;
	assign c_awready = use_host_axi ? 1'b0 : s_awready;

	assign s_wdata = use_host_axi ? h_wdata : c_wdata;
	assign s_wstrb = use_host_axi ? h_wstrb : c_wstrb;
	assign s_wlast = use_host_axi ? h_wlast : c_wlast;
	assign s_wvalid = use_host_axi ? h_wvalid : c_wvalid;
	assign h_wready = use_host_axi ? s_wready : 1'b0;
	assign c_wready = use_host_axi ? 1'b0 : s_wready;

	assign h_bid = s_bid;
	assign c_bid = s_bid;
	assign h_bresp = s_bresp;
	assign c_bresp = s_bresp;
	assign h_bvalid = use_host_axi ? s_bvalid : 1'b0;
	assign c_bvalid = use_host_axi ? 1'b0 : s_bvalid;
	assign s_bready = use_host_axi ? h_bready : c_bready;

	assign s_arid = use_host_axi ? h_arid : c_arid;
	assign s_araddr = use_host_axi ? h_araddr : c_araddr;
	assign s_arlen = use_host_axi ? h_arlen : c_arlen;
	assign s_arsize = use_host_axi ? h_arsize : c_arsize;
	assign s_arburst = use_host_axi ? h_arburst : c_arburst;
	assign s_arlock = use_host_axi ? h_arlock : c_arlock;
	assign s_arcache = use_host_axi ? h_arcache : c_arcache;
	assign s_arprot = use_host_axi ? h_arprot : c_arprot;
	assign s_arregion = use_host_axi ? h_arregion : c_arregion;
	assign s_arqos = use_host_axi ? h_arqos : c_arqos;
	assign s_arvalid = use_host_axi ? h_arvalid : c_arvalid;
	assign h_arready = use_host_axi ? s_arready : 1'b0;
	assign c_arready = use_host_axi ? 1'b0 : s_arready;

	assign h_rid = s_rid;
	assign c_rid = s_rid;
	assign h_rdata = s_rdata;
	assign c_rdata = s_rdata;
	assign h_rresp = s_rresp;
	assign c_rresp = s_rresp;
	assign h_rlast = s_rlast;
	assign c_rlast = s_rlast;
	assign h_rvalid = use_host_axi ? s_rvalid : 1'b0;
	assign c_rvalid = use_host_axi ? 1'b0 : s_rvalid;
	assign s_rready = use_host_axi ? h_rready : c_rready;
`else
	//	Host loader removed: the CPU's 64-bit AXI drives the converter slave directly.
	assign s_awid    = c_awid;
	assign s_awaddr  = c_awaddr;
	assign s_awlen   = c_awlen;
	assign s_awsize  = c_awsize;
	assign s_awburst = c_awburst;
	assign s_awlock  = c_awlock;
	assign s_awcache = c_awcache;
	assign s_awprot  = c_awprot;
	assign s_awregion= c_awregion;
	assign s_awqos   = c_awqos;
	assign s_awvalid = c_awvalid;
	assign c_awready = s_awready;
	assign s_wdata   = c_wdata;
	assign s_wstrb   = c_wstrb;
	assign s_wlast   = c_wlast;
	assign s_wvalid  = c_wvalid;
	assign c_wready  = s_wready;
	assign c_bid     = s_bid;
	assign c_bresp   = s_bresp;
	assign c_bvalid  = s_bvalid;
	assign s_bready  = c_bready;
	assign s_arid    = c_arid;
	assign s_araddr  = c_araddr;
	assign s_arlen   = c_arlen;
	assign s_arsize  = c_arsize;
	assign s_arburst = c_arburst;
	assign s_arlock  = c_arlock;
	assign s_arcache = c_arcache;
	assign s_arprot  = c_arprot;
	assign s_arregion= c_arregion;
	assign s_arqos   = c_arqos;
	assign s_arvalid = c_arvalid;
	assign c_arready = s_arready;
	assign c_rid     = s_rid;
	assign c_rdata   = s_rdata;
	assign c_rresp   = s_rresp;
	assign c_rlast   = s_rlast;
	assign c_rvalid  = s_rvalid;
	assign s_rready  = c_rready;
`endif

	//	===== 64 -> 512 AXI4 data-width converter (Xilinx IP, black box) =====
	//	Confirmed from the generated ddr4_0: the MIG user AXI is 512-bit data /
	//	31-bit address / 64-bit strb (part MT40A256M16GE-083E, 2 GiB). The core's
	//	master is 64-bit, so a width converter is required. Generate
	//	axi_dwidth_converter_0 (SI=64b, MI=512b, 31-bit offset address, same
	//	ui_clk); reconcile its s_axi_*/m_axi_* port names with the generated .veo.
	//
	//	MIG AXI is 0-based (offset within DRAM). The core issues 0x8xxx_xxxx, so
	//	we drop the 0x8000_0000 base by taking [30:0] (the DRAM window is exactly
	//	0x8000_0000..0x8FFF_FFFF, so bit 31 is the base and [30:0] is the offset).
	wire [30:0]				mig_araddr;
	wire [`AXI_LEN_W-1:0]	mig_arlen;  wire [2:0] mig_arsize; wire [1:0] mig_arburst;
	wire					mig_arlock; wire [3:0] mig_arcache; wire [2:0] mig_arprot;
	wire [3:0]				mig_arregion, mig_arqos;
	wire					mig_arvalid, mig_arready;
	wire [`AXI_ID_W-1:0]	mig_rid;    wire [511:0] mig_rdata;
	wire [1:0]				mig_rresp;  wire mig_rlast, mig_rvalid, mig_rready;
	wire [30:0]				mig_awaddr;
	wire [`AXI_LEN_W-1:0]	mig_awlen;  wire [2:0] mig_awsize; wire [1:0] mig_awburst;
	wire					mig_awlock; wire [3:0] mig_awcache; wire [2:0] mig_awprot;
	wire [3:0]				mig_awregion, mig_awqos;
	wire					mig_awvalid, mig_awready;
	wire [511:0]			mig_wdata;  wire [63:0] mig_wstrb;
	wire					mig_wlast, mig_wvalid, mig_wready;
	wire [`AXI_ID_W-1:0]	mig_bid;    wire [1:0] mig_bresp;
	wire					mig_bvalid, mig_bready;

	axi_dwidth_converter_0 u_dwc (
		.s_axi_aclk(ui_clk), .s_axi_aresetn(c0_ddr4_aresetn),
		.s_axi_awid(s_awid), .s_axi_awaddr(s_awaddr), .s_axi_awlen(s_awlen),
		.s_axi_awsize(s_awsize), .s_axi_awburst(s_awburst), .s_axi_awlock(s_awlock),
		.s_axi_awcache(s_awcache), .s_axi_awprot(s_awprot),
		.s_axi_awregion(s_awregion), .s_axi_awqos(s_awqos),
		.s_axi_awvalid(s_awvalid), .s_axi_awready(s_awready),
		.s_axi_wdata(s_wdata), .s_axi_wstrb(s_wstrb), .s_axi_wlast(s_wlast),
		.s_axi_wvalid(s_wvalid), .s_axi_wready(s_wready),
		.s_axi_bid(s_bid), .s_axi_bresp(s_bresp), .s_axi_bvalid(s_bvalid), .s_axi_bready(s_bready),
		.s_axi_arid(s_arid), .s_axi_araddr(s_araddr), .s_axi_arlen(s_arlen),
		.s_axi_arsize(s_arsize), .s_axi_arburst(s_arburst), .s_axi_arlock(s_arlock),
		.s_axi_arcache(s_arcache), .s_axi_arprot(s_arprot),
		.s_axi_arregion(s_arregion), .s_axi_arqos(s_arqos),
		.s_axi_arvalid(s_arvalid), .s_axi_arready(s_arready),
		.s_axi_rid(s_rid), .s_axi_rdata(s_rdata), .s_axi_rresp(s_rresp),
		.s_axi_rlast(s_rlast), .s_axi_rvalid(s_rvalid), .s_axi_rready(s_rready),
		.m_axi_awaddr(mig_awaddr), .m_axi_awlen(mig_awlen),
		.m_axi_awsize(mig_awsize), .m_axi_awburst(mig_awburst),
		.m_axi_awlock(mig_awlock), .m_axi_awcache(mig_awcache),
		.m_axi_awprot(mig_awprot), .m_axi_awregion(mig_awregion),
		.m_axi_awqos(mig_awqos),
		.m_axi_awvalid(mig_awvalid), .m_axi_awready(mig_awready),
		.m_axi_wdata(mig_wdata), .m_axi_wstrb(mig_wstrb), .m_axi_wlast(mig_wlast),
		.m_axi_wvalid(mig_wvalid), .m_axi_wready(mig_wready),
		.m_axi_bresp(mig_bresp), .m_axi_bvalid(mig_bvalid), .m_axi_bready(mig_bready),
		.m_axi_araddr(mig_araddr), .m_axi_arlen(mig_arlen),
		.m_axi_arsize(mig_arsize), .m_axi_arburst(mig_arburst),
		.m_axi_arlock(mig_arlock), .m_axi_arcache(mig_arcache),
		.m_axi_arprot(mig_arprot), .m_axi_arregion(mig_arregion),
		.m_axi_arqos(mig_arqos),
		.m_axi_arvalid(mig_arvalid), .m_axi_arready(mig_arready),
		.m_axi_rdata(mig_rdata), .m_axi_rresp(mig_rresp),
		.m_axi_rlast(mig_rlast), .m_axi_rvalid(mig_rvalid), .m_axi_rready(mig_rready)
	);

	//	===== DDR4 MIG IP (black box; `make mig-vcu118`) =====
	ddr4_0 u_ddr4 (
		.c0_sys_clk_p(c0_sys_clk_p), .c0_sys_clk_n(c0_sys_clk_n),
		.sys_rst(sys_rst),
		.c0_ddr4_adr(c0_ddr4_adr), .c0_ddr4_ba(c0_ddr4_ba), .c0_ddr4_bg(c0_ddr4_bg),
		.c0_ddr4_act_n(c0_ddr4_act_n), .c0_ddr4_cke(c0_ddr4_cke),
		.c0_ddr4_odt(c0_ddr4_odt), .c0_ddr4_cs_n(c0_ddr4_cs_n),
		.c0_ddr4_ck_t(c0_ddr4_ck_t), .c0_ddr4_ck_c(c0_ddr4_ck_c),
		.c0_ddr4_reset_n(c0_ddr4_reset_n),
		.c0_ddr4_dm_dbi_n(c0_ddr4_dm_dbi_n), .c0_ddr4_dq(c0_ddr4_dq),
		.c0_ddr4_dqs_t(c0_ddr4_dqs_t), .c0_ddr4_dqs_c(c0_ddr4_dqs_c),
		.c0_ddr4_ui_clk(ui_clk), .c0_ddr4_ui_clk_sync_rst(ui_clk_sync_rst),
		.c0_init_calib_complete(init_calib_complete),
		.c0_ddr4_aresetn(c0_ddr4_aresetn),
		.c0_ddr4_s_axi_awid(4'b0000), .c0_ddr4_s_axi_awaddr(mig_awaddr),
		.c0_ddr4_s_axi_awlen(mig_awlen), .c0_ddr4_s_axi_awsize(mig_awsize),
		.c0_ddr4_s_axi_awburst(mig_awburst), .c0_ddr4_s_axi_awlock(mig_awlock),
		.c0_ddr4_s_axi_awcache(mig_awcache), .c0_ddr4_s_axi_awprot(mig_awprot),
		.c0_ddr4_s_axi_awqos(mig_awqos),
		.c0_ddr4_s_axi_awvalid(mig_awvalid), .c0_ddr4_s_axi_awready(mig_awready),
		.c0_ddr4_s_axi_wdata(mig_wdata), .c0_ddr4_s_axi_wstrb(mig_wstrb),
		.c0_ddr4_s_axi_wlast(mig_wlast), .c0_ddr4_s_axi_wvalid(mig_wvalid),
		.c0_ddr4_s_axi_wready(mig_wready),
		.c0_ddr4_s_axi_bid(mig_bid), .c0_ddr4_s_axi_bresp(mig_bresp),
		.c0_ddr4_s_axi_bvalid(mig_bvalid), .c0_ddr4_s_axi_bready(mig_bready),
		.c0_ddr4_s_axi_arid(4'b0000), .c0_ddr4_s_axi_araddr(mig_araddr),
		.c0_ddr4_s_axi_arlen(mig_arlen), .c0_ddr4_s_axi_arsize(mig_arsize),
		.c0_ddr4_s_axi_arburst(mig_arburst), .c0_ddr4_s_axi_arlock(mig_arlock),
		.c0_ddr4_s_axi_arcache(mig_arcache), .c0_ddr4_s_axi_arprot(mig_arprot),
		.c0_ddr4_s_axi_arqos(mig_arqos),
		.c0_ddr4_s_axi_arvalid(mig_arvalid), .c0_ddr4_s_axi_arready(mig_arready),
		.c0_ddr4_s_axi_rid(mig_rid), .c0_ddr4_s_axi_rdata(mig_rdata),
		.c0_ddr4_s_axi_rresp(mig_rresp), .c0_ddr4_s_axi_rlast(mig_rlast),
		.c0_ddr4_s_axi_rvalid(mig_rvalid), .c0_ddr4_s_axi_rready(mig_rready)
	);

`ifdef KARU_ETH_PHY
	//	===== DP83867 MDIO management front-end (E3 slice 1) =====
	//	Consumes the sim-validated karu_dp83867_mdio FSM (make mdio-test) via the
	//	karu_eth_phy_fe wrapper (auto-start one-shot + MDIO IOBUF): on reset it holds
	//	PHY RESET_N, soft-resets the PHY, RMW-ensures SGMII_EN/SGMII_AUTONEG_EN, and
	//	reads PHYIDR1 (id_ok when 0x2000). Management path ONLY -- the SGMII datapath
	//	needs the SelectIO/LVDS 1G PCS/PMA (a later slice). id_ok surfaced on led_o[0].
	wire		eth_id_ok;
	wire [15:0]	eth_phy_id;
	wire		eth_mdio_done, eth_mdio_error, eth_mdio_busy;
	karu_eth_phy_fe #(.MDC_DIV(25)) u_eth_phy_fe (	//	75MHz/(2*25) = 1.5MHz MDC (<= 25MHz)
		.clk(clk), .rst(rst),
		.eth_mdc(eth_mdc), .eth_mdio(eth_mdio), .eth_phy_reset_n(eth_phy_reset_n),
		.id_ok(eth_id_ok), .phy_id(eth_phy_id),
		.mdio_done(eth_mdio_done), .mdio_error(eth_mdio_error), .mdio_busy(eth_mdio_busy)
	);
	wire _unused_eth = &{eth_mdio_done, eth_mdio_error, eth_mdio_busy, eth_phy_id, 1'b0};

`ifdef KARU_ETH_SGMII
	//	===== SGMII datapath: 1G Ethernet PCS/PMA (SelectIO/LVDS) <-> DP83867 =====
	//	Per the IP example design (gig_ethernet_pcs_pma_0_example_design.v): core
	//	instantiated directly; refclk625 straight to the LVDS pins (internal buffer);
	//	bitslice/RIU tied off for a single SGMII lane; clk125_out -> the MAC GMII;
	//	config/AN ports match the known-good VCU118 reference (see below). PCS reset is active-high, held while the
	//	core is in reset OR the DP83867 is being physically reset (eth_phy_reset_n low).
	wire		eth_pcs_reset = rst | ~eth_phy_reset_n;
	gig_ethernet_pcs_pma_0 u_pcs (
		.refclk625_p(eth_sgmii_clk_p), .refclk625_n(eth_sgmii_clk_n),
		.txp_0(eth_sgmii_txp), .txn_0(eth_sgmii_txn),
		.rxp_0(eth_sgmii_rxp), .rxn_0(eth_sgmii_rxn),
		.signal_detect_0(1'b1),
		.gmii_txd_0(eth_gmii_txd), .gmii_tx_en_0(eth_gmii_tx_en), .gmii_tx_er_0(eth_gmii_tx_er),
		.gmii_rxd_0(eth_gmii_rxd), .gmii_rx_dv_0(eth_gmii_rx_dv), .gmii_rx_er_0(eth_gmii_rx_er),
		.gmii_isolate_0(),
		.sgmii_clk_r_0(), .sgmii_clk_f_0(), .sgmii_clk_en_0(),
		//	speed_is_*: tie to 1000 (both 0). The LiteEthPHYGMII MAC runs a FIXED
		//	125 MHz / 8-bit GMII (1000 Mbps only -- no 10/100 rate switch like the
		//	alexforencich reference MAC), so the PCS must stay in 1000 mode.
		.speed_is_10_100_0(1'b0), .speed_is_100_0(1'b0),
		.an_interrupt_0(),
		//	SGMII AN config -- MATCH the known-good VCU118 reference (alexforencich
		//	verilog-ethernet example/VCU118/fpga_1g, SAME IP config: SGMII/LVDS/625/
		//	SGMII_PHY_Mode=false/AN=true): advertise link(15)+ack(14)+full-duplex(12)+
		//	speed=1000(11)+SGMII(0) = 0xD801. (Was 0x0021 -- wrong, AN never resolved.)
		.an_adv_config_vector_0(16'hD801),
		.an_restart_config_0(1'b0),
		.status_vector_0(eth_pcs_status),
		//	configuration_vector[4] = AUTO-NEGOTIATION ENABLE. Was 5'b00000 -> AN
		//	DISABLED at runtime, so the PCS never ran the SGMII AN handshake with the
		//	DP83867 and the RX never synced (status stuck rudi_invalid, link=0). The
		//	reference sets bit 4; [3:0]=isolate/powerdown/loopback/unidir all off.
		.configuration_vector_0(5'b10000),
		.rst_125_out(),
		.clk125_out(eth_clk125), .clk312_out(),
		.riu_rddata_3(16'b0), .riu_valid_3(1'b0), .riu_prsnt_3(1'b0),
		.riu_rddata_2(16'b0), .riu_valid_2(1'b0), .riu_prsnt_2(1'b0),
		.riu_rddata_1(16'b0), .riu_valid_1(1'b0), .riu_prsnt_1(1'b0),
		.tx_dly_rdy_1(1'b1), .rx_dly_rdy_1(1'b1), .rx_vtc_rdy_1(1'b1), .tx_vtc_rdy_1(1'b1),
		.tx_dly_rdy_2(1'b1), .rx_dly_rdy_2(1'b1), .rx_vtc_rdy_2(1'b1), .tx_vtc_rdy_2(1'b1),
		.tx_dly_rdy_3(1'b1), .rx_dly_rdy_3(1'b1), .rx_vtc_rdy_3(1'b1), .tx_vtc_rdy_3(1'b1),
		.reset(eth_pcs_reset)
	);
`endif

	assign led_o = { trap, host_cpu_hold, uart_txd, usb_uart_rts_o,
					 usb_uart_cts_i, init_calib_complete, ~rst, eth_id_ok };
`else
	assign led_o = { trap, host_cpu_hold, uart_txd, usb_uart_rts_o,
					 usb_uart_cts_i, init_calib_complete, ~rst, 1'b1 };
`endif
`ifdef KARU_DDR_HOST_DBG
	wire _unused_axi_region = &{mig_awregion, mig_arregion, j_awlock,
								j_awcache, j_awprot, j_awqos, j_arlock,
								j_arcache, j_arprot, j_arqos, 1'b0};
`else
	wire _unused_axi_region = &{mig_awregion, mig_arregion, eth_status_ui, 1'b0};
`endif
endmodule
`endif
